version: "3.5"

services:
  app1:
    build:
      context: ./app1
    command: nodemon --inspect=0.0.0.0:9229 ./src
    ports:
      - "3001:3000"
    volumes:
      - ./app1:/app
      - /app/node_modules

  app2:
    build:
      context: ./app2
    command: nodemon --inspect=0.0.0.0:9229 ./src
    ports:
      - "3002:3000"
    volumes:
      - ./app2:/app
      - /app/node_modules

  app3:
    build:
      context: ./app3
    command: nodemon --inspect=0.0.0.0:9229 ./src
    ports:
      - "3003:3000"
    volumes:
      - ./app3:/app
      - /app/node_modules
